name: "Run Templater"
on:
  workflow_dispatch:
env:
  GIT_LOGIN: ${{ secrets.GIT_LOGIN }}
  GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
jobs:
  execute:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
      - name: "Install JDK 21"
        uses: "actions/setup-java@v4"
        with:
          java-version: "21"
          distribution: "corretto"
      - name: "Install Gradle"
        uses: "gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5"
      - name: "Run Templater"
        run: "gradle bootRun --args='--git.credentials.login=${GIT_LOGIN} --git.credentials.password=${GIT_PASSWORD}'"
